### ISSUE TITLE
Issues with importing TCX workout to Polar Flow with RunGap or SyncMyTracks

### ISSUE THREAD

**Issue by kRycco** [svenmeier/coxswain#117]
To get workout in to Flow I first have to import TCX to some other place and I am useing Garmin Connect for that.
After that I can run RunGap on Iphone or SyncMyTracks on Android to Import my aktivity to Flow.

I have 3 issues with WaterRower recorded with Coswain, that I don't have with Concept 2 recorded with ErgData app.
1. When I use SyncMyTracks to syncronize Connect with Flow there are no stroke graph data.

2. When I use RunGap to syncronize Connect with Flow, the aktivity refuses to open in Flow.

3. When I use Coswain I get a map in the aktivity that I don't have in ErgData and don't want to have.

**Comment by inonoob** [comment]
Hey @kRycco, 

Let me try to answer some of the question and ask some :) 

R1: It is known that Garmin has issue with the strokes and TCX file (https://github.com/svenmeier/coxswain/issues/69) 
I tried it yesterday again and garmin don't take the strokes in the first place. So if you export your file from garmin it woun't export it aswell. I tried a lot of stuff to get it work but garmin won't track the strokes. Even if you respect the TCX nomenclature to the letter. With their new file format "FIT" it is working but their is no converter for coxswain tcx file to FIT files. 

R2. I don't have apple so, I can't check what is wrong. 

R3. This is due to the fact that Coxswain puts gps values into the TCX file. ==> possible improvement choose to not include gps data in the export. 

Q1: How does a ErgData looks like. Is it a TCX file or a FIT file ? 
may you post an extract of the ErgData file 

Best Regards

**Comment by kRycco** [comment]
Hej @inonoob

R1. I missed that.

R1. Okey

R3. I try with the GPS off next time then.

Q1. I can't access this files on the Iphone, don't know how to do that.
There are no way to export aktivity from Concect log site manually.
ErgData sync to https://log.concept2.com/log and in user profile there are 4 applications to connect with granted permissions to access for export. There are Strava, Training Peak, Fitbit and Garmin Connect.

Here are Garmin aktivity recorded with ErgData synced to concept with forward connection to Garmin.

https://connect.garmin.com/modern/activity/5737014380

Here are ErgIQ aktivity on Fenix 6 connected to PM5.

https://connect.garmin.com/modern/activity/5737021138

And here are Polar Flow imported with RunGap from Garmin Connect ErgData aktivity.

https://flow.polar.com/training/analysis/5282095288

//Kent

Skickades från E-post<https://go.microsoft.com/fwlink/?LinkId=550986> för Windows 10

Från: inonoob<mailto:notifications@github.com>
Skickat: den 4 november 2020 14:19
Till: svenmeier/coxswain<mailto:coxswain@noreply.github.com>
Kopia: kRycco<mailto:gronvik@hotmail.com>; Mention<mailto:mention@noreply.github.com>
Ämne: Re: [svenmeier/coxswain] Issues with importing TCX workout to Polar Flow with RunGap or SyncMyTracks (#117)


Hey @kRycco<https://github.com/kRycco>,

Let me try to answer some of the question and ask some :)

R1: It is known that Garmin has issue with the strokes and TCX file (#69<https://github.com/svenmeier/coxswain/issues/69>)
I tried it yesterday again and garmin don't take the strokes in the first place. So if you export your file from garmin it woun't export it aswell. I tried a lot of stuff to get it work but garmin won't track the strokes. Even if you respect the TCX nomenclature to the letter. With their new file format "FIT" it is working but their is no converter for coxswain tcx file to FIT files.

R2. I don't have apple so, I can't check what is wrong.

R3. This is due to the fact that Coxswain puts gps values into the TCX file. ==> possible improvement choose to not include gps data in the export.

Q1: How does a ErgData looks like. Is it a TCX file or a FIT file ?
may you post an extract of the ErgData file

Best Regards

**Comment by kRycco** [comment]
[2020-10-27 18 44 26 +0000.log](https://github.com/svenmeier/coxswain/files/5538936/2020-10-27.18.44.26.%2B0000.log)

Attached ErgData file, exported from Iphone with IMazing.

**Comment by inonoob** [comment]
So from the log, I can see that the ErgData uploads it to the logbook and at the end I thing that the logbook change those data in the back-end to fit the Garmin connect needed format. It might be that the logbook changes or even encodes the training session in a FIT file which is then uploaded via the Garmin connect api. 
But I don't have any information on that-
