### ISSUE TITLE
Problem with Bluetooth Com Module

### ISSUE THREAD

**Issue by Magroll** [svenmeier/coxswain#137]
Hi, I got shipped my S4 COM Module from sport-tiedje.de today
I have very strange behavior with the connection from it to Coxswain, when start with rowing :(
It's all out of sync and the time is sometimes stopping completely...

I've installed the nRF Connect for Mobile to check my Versions and got the following Results:
Hardware: 2.2BLE
Firmware: 0.30
Software: 1.30

I didn't found any Infos regarding this software Version in the Wiki, there is only mentioned the 4.0 and greater versions...
Have I got an very old S4 BT Module Version?
Could I install the Firmwareupdate to 4.x?
Should I send it back?

Thank you very much for your great software (use it via USB for 3 Weeks now and want to "upgrade" to BT) and any help will be appreciated.

**Comment by Magroll** [comment]
Just found other (closed) issues with the same Problem (SW Version 1.30).
As far as I could read there is no solution without (For now I'd recommend you to return your module, if possible.)
Is this still the case, or are there any other solutions actually? 
Do you have any Tipps how to get sure, to got an actual Com Module, if I send it back and order a new one?

Thank you very much!

**Comment by svenmeier** [comment]
Hi @Magroll,
regretfully Waterrower seems to have (at least) two different manufacturers for their Comm modules.
I had enough troubles getting mine to work correctly already. It's really strange why all these devices differ in their behavior, since after all they are supposed to be standard Bluetooth LE devices, which should work with any client.

It would be interesting, whether your device works with the standard app https://play.google.com/store/apps/details?id=com.label305.waterrower

If you're really adventurous, you could send me the device, I take a look at it and I forward it to nohrd, if we can't get it to work.
Returning it immediately is the easiest solution.

It seems to me, Waterrower has abandoned the Comm and is pushing for SmartRow instead :(.

**Comment by Magroll** [comment]
Hi Sven please contact me directly on Prophet73@gmx.de for more details regarding the possibilities of an adventure. ;o)

**Comment by svenmeier** [comment]
Module worked fine on my S4.
