### ISSUE TITLE
Feature suggestion: record Bluetooth LE heart rate data

### ISSUE THREAD

**Issue by Jo11n** [svenmeier/coxswain#22]
Waterrower S4 supports heart rate data. However, it requires a pricey ANT+ kit. It would be extremely cool if coxswain could independently support the bluetooth LE (/"smart") heart rate protocol. This would allow to use inexpensive, run of the mill third party sensors. Thanks for considering this.

**Comment by svenmeier** [comment]
Yes, Waterrower's ANT+ kit is pricey - I know it because I bought it :P.

Reading this data directly from a bluetooth device sounds like a nice alternative. I'll investigate.

**Comment by svenmeier** [comment]
Actually with Google Fit we might be able to read the heart rate from any input (including BLE devices) with DataType.TYPE_HEART_RATE_BPM:

    https://developers.google.com/fit/android/sensors

**Comment by svenmeier** [comment]
I decided against using Google Fit sensors for this.

Starting with the next version you'll be able to choose bluetooth or device sensors to record heart rate.

**Comment by claes** [comment]
I am looking to buy a heart rate sensor for using with this app. But I have no experience in them and not sure what I best should look for, if there is something that is reliable and preferably inexpensive. What does "device sensor" mean.. ? Is it some kind of native sensor to Android?  I have tried to pair my Android Wear (Huawei Watch which has a hearth sensor) with the app and failed.

**Comment by svenmeier** [comment]
Hi Cleas,

with "device sensor" Coxswain will read the heart rate directly from sensors built into your device. I would expect this to work with connected android wear devices too, but I never actually tried it because I have none.
Please open a new issue if you can't get it to work with your Huawei Watch.

Bluetooth is an alternative: any Bluetooth heart rate monitor that your are able to use with your Android device should work with Coxswain too.
I had good results with "BerryKing Heartbeat Bluetooth & Ant+".
