### ISSUE TITLE
Feature: Configurable kcal calculation

### ISSUE THREAD

**Issue by svenmeier** [svenmeier/coxswain#5]
With configurable body weight and water level Coxswain could implement its own (improved) kcal calculation, instead of reading this value from the Waterrower.

**Comment by svenmeier** [comment]
Seems people are satisfied what Waterrower is generating at the moment.

**Comment by kosli** [comment]
I would definitely be interested in a configurable weigth option as I am not the only one using the WaterRower so that the kcal would be calculated properly.

**Comment by svenmeier** [comment]
If we allow users to specify their weight, Coxswain could adjust the kcal energy easily.
But what formula should we use?

I've found the following for the Concept 2:

    True calories/hour burned = Calories on the PM - 300 + (1.714 * weight)
    Calorie burn for your workout = (True calories/hour burned * duration in seconds)/3600

**Comment by svenmeier** [comment]
Upcoming version 3.7 will allow to specify body weight, which is used to adjust the kcal reported by Waterrower.

**Comment by kosli** [comment]
@svenmeier thanks, looking forward for it.

**Comment by Jo11n** [comment]
I played around with this a little bit today. Are you using the concept2 conversion as is? I assuming this is the case because when I enter 79.5 kg (175 pounds) into coxswain, I will get the same kcal values in coxswain as displayed on the S4. However, according to this [Facebook post by watterrower] (https://www.facebook.com/WaterRower/posts/930624596988532:0), the S4 kcal calculation assumes a body weight of 150 pounds (68.039 kg).  Wouldn't the conversion have to be adjusted to this value?

If I understand correctly, the conversion simply adds a body-weight adjusted constant (which is 300 kcal/hour at 175 pounds) to the estimated energy expenditure due to rowing. Using the same gradient as the concept2, this constant would be 257.1 kcal/hour for a rower of 150 pounds as assumed by the waterrower.  Thus, the adjusted formula would be
`True calories/hour burned = Calories on the waterrower - 257.1 + (1.714 * weight_in_pounds)`

additional minor issue: I had to kill and restart coxswain to use a new kg setting.

**Comment by svenmeier** [comment]
I fiddled with some constants until the results made some sense, but tbh I don't have much experience in workout energy.

Could you please take a look at https://docs.google.com/spreadsheets/d/1Ef0EGcxOb8Q16UxTsrurwFuumIhm4SYjpIKlrbys3h0/edit?usp=sharing ?
I've added a column with your proposed formula - do you think the values are better?

**Comment by Jo11n** [comment]
Yes, that's what I had in mind. I am no expert either, but my guess is that unless Waterrower reveals their formulas and data, there's not much more that can be done. 

Now, the adjusted estimate would center around the alleged 150 pounds Waterrower default, but use the same linear gradient as in the concept2 adjustment - just with a different starting point. 

This is going to be a pretty rough approximation to begin with, however. The concept2 folks say that their estimate is based on lab testing (can't find the forum post anymore). I am guessing they used linear regression to predict energy expenditure by body weight. I don't see why this should be much different for the Waterrower, but I may be mistaken.  However, there must be a ton of other factors that produce more variability between people (e. g. rowing technique efficiency). It's going to be somewhere in the right ballpark, though.

**Comment by svenmeier** [comment]
Thanks for your help  - I'll update the formula in the next Coxswain version as you have proposed.
